# Generated by Django 5.0 on 2023-12-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teachers_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detentions',
            new_name='Detention',
        ),
        migrations.RenameModel(
            old_name='Guardians',
            new_name='Guardian',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
