# Generated by Django 5.0 on 2023-12-31 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_detention_created_at_detention_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detention',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='detention',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detention',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
